// Code generated by "stringer -type Flag"; DO NOT EDIT

package gocmd

import "fmt"

const _Flag_name = "MustExitMustPanicWarnVerbosePassThrough"

var _Flag_index = [...]uint8{0, 8, 17, 21, 28, 39}

func (i Flag) String() string {
	i -= 1
	if i < 0 || i >= Flag(len(_Flag_index)-1) {
		return fmt.Sprintf("Flag(%d)", i+1)
	}
	return _Flag_name[_Flag_index[i]:_Flag_index[i+1]]
}
